import type { EventItem, DashboardStats, KnowledgeArticle, DetectionResult, DispatchItem, ResidentProfile, EmergencyPlan } from '@/types';

export const mockDetectionResults: DetectionResult[] = [
  { label: '人员摔倒', confidence: 0.94, bbox: { x: 280, y: 180, w: 220, h: 300 }, category: 'fall' },
  { label: '长时间静止', confidence: 0.88, category: 'still' },
  { label: '周围无人响应', confidence: 0.81, category: 'no_response' },
];

export const mockDetectionImage = 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1280&h=720&fit=crop';

export const mockEvents: EventItem[] = [
  {
    id: 'evt-20250501-001',
    type: '摔倒未响应',
    risk: '紧急',
    riskLevel: 'critical',
    zone: 'A栋-3层-走廊',
    camera: 'CAM-A3-01',
    time: '2025-05-01 03:12:05',
    status: '待处理',
    handler: '张晓婷',
    confidence: 0.94,
    summary: '夜间巡检捕捉到老人在走廊转弯处跌倒，12 秒内未出现明显移动，周围未检测到护理人员靠近。',
    decision: {
      riskScore: 92,
      riskLevel: 'critical',
      cause: '走廊湿滑 + 姿态角度异常',
      suggestion: '立即通知最近护理员前往现场，保持老人原地状态，避免盲目移动，记录事件并生成护理报告。',
      basis: ['姿态角度异常', '持续静止时间超过阈值', '周围无人响应', '场景位于走廊转角，存在二次碰撞风险'],
      knowledgeRefs: ['跌倒应急处理流程', '康养机构夜间巡护规范', '老年人突发疾病初步处置指南'],
    },
    detections: [
      { label: '人员摔倒', confidence: 0.94, bbox: { x: 280, y: 180, w: 220, h: 300 }, category: 'fall' },
      { label: '长时间静止', confidence: 0.88, category: 'still' },
      { label: '周围无人响应', confidence: 0.81, category: 'no_response' },
    ],
  },
  {
    id: 'evt-20250501-002',
    type: '夜间离床未归',
    risk: '高风险',
    riskLevel: 'high',
    zone: 'B栋-5层-房间508',
    camera: 'CAM-B5-R508',
    time: '2025-05-01 02:16:33',
    status: '已通知',
    handler: '李建国',
    confidence: 0.87,
    summary: '老人凌晨 2 点离开床位前往卫生间，超过 15 分钟仍未返回，结合行动轨迹判断可能存在跌倒或迷路风险。',
    decision: {
      riskScore: 81,
      riskLevel: 'high',
      cause: '行动不便 + 超时未归',
      suggestion: '优先确认是否在卫生间内滞留，必要时安排护工陪同返回床位。',
      basis: ['离床时间超过安全阈值', '行动轨迹中断', '夜间高风险时段'],
      knowledgeRefs: ['夜间离床风险处置规范', '跌倒应急处理流程'],
    },
  },
  {
    id: 'evt-20250501-003',
    type: '烟火疑似异常',
    risk: '高风险',
    riskLevel: 'high',
    zone: 'C栋-1层-茶水间',
    camera: 'CAM-C1-Lounge',
    time: '2025-05-01 11:05:18',
    status: '已处理',
    handler: '王美华',
    confidence: 0.91,
    summary: '茶水间出现持续性烟雾浓度上升，系统联动现场喊话后，工作人员已完成处置，确认为电器加热异常。',
    decision: {
      riskScore: 78,
      riskLevel: 'high',
      cause: '设备加热异常 + 通风不良',
      suggestion: '检查茶歇区电器设备运行状态，排查通风口堵塞情况。',
      basis: ['烟雾浓度持续上升', '热源位置异常', '通风系统未正常运转'],
      knowledgeRefs: ['火灾隐患初步处理流程', '康养机构烟雾与设备异常判断规则'],
    },
  },
  {
    id: 'evt-20250501-004',
    type: '长时间滞留',
    risk: '中风险',
    riskLevel: 'medium',
    zone: 'A栋-1层-电梯口',
    camera: 'CAM-A1-Entry',
    time: '2025-05-01 16:30:45',
    status: '观察中',
    handler: '赵文强',
    confidence: 0.82,
    summary: '电梯口区域检测到一名老人长时间滞留，结合行为分析可能是等待电梯或迷路。',
    decision: {
      riskScore: 58,
      riskLevel: 'medium',
      cause: '入口指引不足 + 夜间前台人手减少',
      suggestion: '安排前台或志愿者引导，并增加入口区域指引标识。',
      basis: ['滞留时间超过 10 分钟', '场景为公共通道', '可能存在迷路风险'],
      knowledgeRefs: ['护理员巡房记录标准'],
    },
  },
  {
    id: 'evt-20250501-005',
    type: '久卧未动',
    risk: '高风险',
    riskLevel: 'high',
    zone: 'B栋-3层-房间302',
    camera: 'CAM-B3-R302',
    time: '2025-05-01 08:42:10',
    status: '待处理',
    handler: '张晓婷',
    confidence: 0.89,
    summary: '床位区域连续 50 分钟未检测到翻身或起身动作，存在压疮和低体温风险。',
    decision: {
      riskScore: 81,
      riskLevel: 'high',
      cause: '长时间体位固定 + 室温下降',
      suggestion: '安排巡护查看被褥情况，确认老人是否需要更换体位或调整室温。',
      basis: ['体位固定超过 30 分钟', '室温低于安全阈值', '被褥状态异常'],
      knowledgeRefs: ['久卧未动与压疮风险评估', '老年人突发疾病观察要点'],
    },
  },
  {
    id: 'evt-20250501-006',
    type: '离床未归',
    risk: '中风险',
    riskLevel: 'medium',
    zone: 'C栋-2层-洗手间通道',
    camera: 'CAM-C2-Corridor',
    time: '2025-05-01 02:56:09',
    status: '已通知',
    handler: '李建国',
    confidence: 0.79,
    summary: '老人离开床位后前往卫生间，超过预期时间仍未返回。',
    decision: {
      riskScore: 63,
      riskLevel: 'medium',
      cause: '行动不便',
      suggestion: '优先确认是否在卫生间内滞留，必要时安排护工陪同返回床位。',
      basis: ['离床时间超过安全阈值', '行动轨迹中断'],
      knowledgeRefs: ['夜间离床风险处置规范'],
    },
  },
  {
    id: 'evt-20250501-007',
    type: '冲突',
    risk: '低风险',
    riskLevel: 'low',
    zone: 'A栋-2层-活动室',
    camera: 'CAM-A2-Activity',
    time: '2025-05-01 14:22:17',
    status: '已处理',
    handler: '王美华',
    confidence: 0.76,
    summary: '活动室中两名老人出现争执动作，系统结合语义理解判断为轻微冲突。',
    decision: {
      riskScore: 35,
      riskLevel: 'low',
      cause: '公共空间资源使用冲突',
      suggestion: '由护理员现场安抚并协助分隔活动区域。',
      basis: ['肢体语言分析', '声纹情绪识别'],
      knowledgeRefs: [],
    },
  },
  {
    id: 'evt-20250501-008',
    type: '摔倒',
    risk: '紧急',
    riskLevel: 'critical',
    zone: 'B栋-1层-楼梯口',
    camera: 'CAM-B1-Stair',
    time: '2025-05-01 09:15:33',
    status: '已处理',
    handler: '赵文强',
    confidence: 0.96,
    summary: '老人在楼梯口失去平衡摔倒，护理员 2 分钟内赶到现场，初步判断无骨折。',
    decision: {
      riskScore: 88,
      riskLevel: 'critical',
      cause: '楼梯湿滑 + 步态不稳',
      suggestion: '确认老人身体状况，安排医护检查，排查楼梯防滑措施。',
      basis: ['姿态角度异常', '碰撞检测', '跌倒高度评估'],
      knowledgeRefs: ['跌倒应急处理流程', '老年人突发疾病初步处置指南'],
    },
  },
  {
    id: 'evt-20250501-009',
    type: '无人看护',
    risk: '中风险',
    riskLevel: 'medium',
    zone: 'C栋-3层-康复区',
    camera: 'CAM-C3-Rehab',
    time: '2025-05-01 15:48:22',
    status: '待处理',
    handler: '张晓婷',
    confidence: 0.84,
    summary: '康复训练区有 3 名老人在活动，但未检测到护理人员在场，存在安全隐患。',
    decision: {
      riskScore: 65,
      riskLevel: 'high',
      cause: '护理人员不在岗 + 老人正在活动',
      suggestion: '立即通知康复区值班护理员到岗，确认是否有紧急情况需要支援。',
      basis: ['人员密度分析', '护理人员缺失', '活动区域风险'],
      knowledgeRefs: ['护理员巡房记录标准'],
    },
  },
  {
    id: 'evt-20250501-010',
    type: '异常滞留',
    risk: '低风险',
    riskLevel: 'low',
    zone: 'A栋-1层-花园入口',
    camera: 'CAM-A1-Garden',
    time: '2025-05-01 10:30:05',
    status: '已处理',
    handler: '王美华',
    confidence: 0.72,
    summary: '花园入口处一名老人长时间停留，经确认是在等家属探望。',
    decision: {
      riskScore: 28,
      riskLevel: 'low',
      cause: '等待家属 + 天气较热',
      suggestion: '建议引导老人到阴凉处等候，提供饮水。',
      basis: ['滞留时间分析', '场景语义判断'],
      knowledgeRefs: [],
    },
  },
];

export const mockDashboard: DashboardStats = {
  todayEvents: 133,
  retainedCritical: 7,
  handledRate: 88.7,
  avgResponseMinutes: 4.2,
  riskTypeDistribution: [
    { name: '摔倒', value: 26 },
    { name: '久卧未动', value: 22 },
    { name: '烟火', value: 17 },
    { name: '异常滞留', value: 19 },
    { name: '离床未归', value: 14 },
    { name: '冲突', value: 12 },
    { name: '无人看护', value: 15 },
    { name: '长时间滞留', value: 8 },
  ],
  weeklyCriticalTrend: [
    { day: '周一', value: 9 },
    { day: '周二', value: 12 },
    { day: '周三', value: 8 },
    { day: '周四', value: 11 },
    { day: '周五', value: 14 },
    { day: '周六', value: 7 },
    { day: '周日', value: 6 },
  ],
  zoneHotspots: [
    { zone: 'A栋-3层', score: 89 },
    { zone: 'B栋-5层', score: 76 },
    { zone: 'C栋-1层', score: 72 },
    { zone: 'A栋-1层', score: 64 },
    { zone: 'B栋-2层', score: 58 },
  ],
};

export const mockKnowledge: KnowledgeArticle[] = [
  {
    id: 'kb-001',
    title: '跌倒应急处理流程',
    tags: ['摔倒', '应急', '处置流程'],
    content: '1. 发现老人跌倒后，立即前往现场确认状态；2. 判断老人意识是否清醒，切勿盲目搬动；3. 如有外伤或疑似骨折，保持原地不动并联系医护人员；4. 记录事件时间、地点、跌倒姿势等关键信息；5. 事后填写护理报告并通知家属。',
    updatedAt: '2025-04-28',
    scenario: '适用于所有区域检测到老人跌倒的紧急事件',
  },
  {
    id: 'kb-002',
    title: '夜间离床风险处置规范',
    tags: ['离床', '夜间', '巡护'],
    content: '1. 系统检测到老人离床超过 10 分钟未归时自动预警；2. 护理员应优先检查卫生间和走廊；3. 如老人在卫生间滞留，轻声询问是否需要帮助；4. 如老人跌倒在地面，立即启动跌倒应急流程；5. 建议在床边和走廊增设夜灯降低夜间风险。',
    updatedAt: '2025-04-25',
    scenario: '适用于夜间 22:00 至次日 6:00 的离床未归事件',
  },
  {
    id: 'kb-003',
    title: '火灾隐患初步处理流程',
    tags: ['烟火', '火灾', '安全'],
    content: '1. 系统检测到烟雾浓度异常时立即触发预警；2. 确认烟雾来源位置，判断是否为设备故障；3. 如确认为明火，立即启动消防疏散流程；4. 如为设备加热异常，关闭电源并通风；5. 所有烟火事件必须填写专项报告并上报安全主管。',
    updatedAt: '2025-04-20',
    scenario: '适用于茶水间、厨房、设备间等高风险区域',
  },
  {
    id: 'kb-004',
    title: '护理员巡房记录标准',
    tags: ['巡房', '记录', '标准'],
    content: '1. 白班每 2 小时巡房一次，夜班每 1.5 小时巡房一次；2. 巡房时需确认每位老人的体位、呼吸、被褥状态；3. 发生任何异常事件需在 5 分钟内记录并上报；4. 巡房记录需包含时间、区域、检查项、异常情况；5. 系统将自动比对巡房记录与视频检测结果。',
    updatedAt: '2025-04-15',
    scenario: '适用于所有护理区域的日常巡检管理',
  },
  {
    id: 'kb-005',
    title: '老年人突发疾病观察要点',
    tags: ['突发疾病', '观察', '急救'],
    content: '1. 注意观察老人面色、呼吸频率、肢体动作是否异常；2. 如出现意识模糊、言语不清、单侧肢体无力，疑似脑卒中，立即拨打 120；3. 如出现胸痛、出汗、呼吸困难，疑似心梗，保持半卧位并呼叫急救；4. 所有突发疾病事件需在 3 分钟内通知值班医护；5. 保持老人呼吸道通畅，避免围观。',
    updatedAt: '2025-04-10',
    scenario: '适用于系统检测到久卧、异常姿态等疑似疾病相关事件',
  },
];

export const architectureLayers = [
  { title: '前端展示层', technologies: 'Next.js / React / Tailwind CSS', description: '打造可视化安全巡护界面，让护理员一看就知道先处理哪件事', accent: 'from-orange-400/20 to-amber-200/5' },
  { title: '视觉感知层', technologies: 'YOLO / Pose Estimation / Video Understanding', description: '让摄像头自己看懂画面，识别摔倒、久卧、烟火等风险事件', accent: 'from-emerald-400/20 to-emerald-200/5' },
  { title: '行为理解层', technologies: '时序分析 / 场景关系判断 / 风险规则引擎', description: '从"看到"升级为"看懂"，理解动作含义和场景上下文', accent: 'from-sky-400/20 to-cyan-200/5' },
  { title: '智能决策层', technologies: 'LLM Agent / RAG 知识库 / 风险评分', description: '不只是报警，还能给出判断依据和处置建议', accent: 'from-violet-400/20 to-fuchsia-200/5' },
  { title: '数据管理层', technologies: '事件记录 / 处置流程 / 数据看板', description: '形成从检测到处置的完整闭环，数据可追溯', accent: 'from-rose-400/20 to-rose-200/5' },
];

export const apiEndpoints = [
  { method: 'POST', path: '/api/vision/detect', description: '上传图片/视频，接入 YOLO 目标检测和姿态估计', status: 'mock' },
  { method: 'POST', path: '/api/behavior/analyze', description: '行为偏离度分析和风险趋势评估', status: 'mock' },
  { method: 'POST', path: '/api/decision/evaluate', description: '接收视觉识别结果，调用大模型生成风险决策', status: 'mock' },
  { method: 'GET', path: '/api/dispatch/queue', description: '获取调度优先级队列', status: 'mock' },
  { method: 'POST', path: '/api/dispatch/assign', description: '指派护理员处理事件', status: 'mock' },
  { method: 'GET', path: '/api/events', description: '获取风险事件列表，支持筛选和排序', status: 'mock' },
  { method: 'GET', path: '/api/events/:id', description: '获取单个事件详情，含检测结果和决策建议', status: 'mock' },
  { method: 'GET', path: '/api/dashboard/stats', description: '获取数据看板统计信息', status: 'mock' },
  { method: 'GET', path: '/api/emergency/plans', description: '获取应急方案列表', status: 'mock' },
  { method: 'POST', path: '/api/emergency/plans', description: '执行应急步骤（开始/完成/跳过）', status: 'mock' },
  { method: 'GET', path: '/api/knowledge', description: '搜索知识库内容，后期接入 RAG', status: 'mock' },
];

export const mockDispatchQueue: DispatchItem[] = [
  {
    id: 'dsp-001',
    eventId: 'evt-20250501-001',
    type: '摔倒未响应',
    risk: '紧急',
    riskLevel: 'critical',
    zone: 'A栋-3层-走廊',
    waitMinutes: 8,
    residentName: '张建国',
    priority: 1,
    priorityScore: 100,
    reason: '风险等级为紧急，老人跌倒后超过 3 分钟未出现明显移动，周围无护理人员，已超过黄金响应时间。',
    status: '待指派',
    time: '2025-05-01 03:12:05',
  },
  {
    id: 'dsp-002',
    eventId: 'evt-20250501-008',
    type: '楼梯口摔倒',
    risk: '紧急',
    riskLevel: 'critical',
    zone: 'B栋-1层-楼梯口',
    waitMinutes: 3,
    residentName: '刘德华',
    priority: 2,
    priorityScore: 95,
    reason: '楼梯口摔倒存在二次碰撞风险，且楼梯湿滑，需要优先确认是否骨折。',
    status: '处理中',
    assignee: '赵文强',
    time: '2025-05-01 09:15:33',
  },
  {
    id: 'dsp-003',
    eventId: 'evt-20250501-005',
    type: '久卧未动',
    risk: '高风险',
    riskLevel: 'high',
    zone: 'B栋-3层-房间302',
    waitMinutes: 22,
    residentName: '王秀兰',
    priority: 3,
    priorityScore: 83,
    reason: '床位连续 50 分钟未检测到翻身动作，存在压疮和低体温风险，且室温低于安全阈值。',
    status: '待指派',
    time: '2025-05-01 08:42:10',
  },
  {
    id: 'dsp-004',
    eventId: 'evt-20250501-002',
    type: '夜间离床未归',
    risk: '高风险',
    riskLevel: 'high',
    zone: 'B栋-5层-房间508',
    waitMinutes: 15,
    residentName: '陈国华',
    priority: 4,
    priorityScore: 79,
    reason: '老人行动不便，凌晨离床超过 15 分钟未归，跌倒风险较高。',
    status: '待指派',
    time: '2025-05-01 02:16:33',
  },
  {
    id: 'dsp-005',
    eventId: 'evt-20250501-003',
    type: '烟火疑似异常',
    risk: '高风险',
    riskLevel: 'high',
    zone: 'C栋-1层-茶水间',
    waitMinutes: 5,
    residentName: '—',
    priority: 5,
    priorityScore: 77,
    reason: '茶水间烟雾浓度持续上升，可能涉及电器故障，需要确认设备状态和通风口。',
    status: '待指派',
    time: '2025-05-01 11:05:18',
  },
  {
    id: 'dsp-006',
    eventId: 'evt-20250501-009',
    type: '无人看护',
    risk: '中风险',
    riskLevel: 'medium',
    zone: 'C栋-3层-康复区',
    waitMinutes: 18,
    residentName: '多名老人',
    priority: 6,
    priorityScore: 72,
    reason: '康复区有 3 名老人活动但无护理人员在场，存在安全隐患。',
    status: '待指派',
    time: '2025-05-01 15:48:22',
  },
  {
    id: 'dsp-007',
    eventId: 'evt-20250501-004',
    type: '长时间滞留',
    risk: '中风险',
    riskLevel: 'medium',
    zone: 'A栋-1层-电梯口',
    waitMinutes: 25,
    residentName: '李明辉',
    priority: 7,
    priorityScore: 67,
    reason: '老人在电梯口滞留超过 10 分钟，可能存在迷路风险，需确认是否需要引导。',
    status: '待指派',
    time: '2025-05-01 16:30:45',
  },
];

export const mockResidentProfiles: ResidentProfile[] = [
  {
    id: 'res-001',
    name: '张建国',
    room: 'A栋-301',
    age: 78,
    riskTags: ['摔倒高危', '高血压'],
    todayStatus: '夜间走廊跌倒，待处理',
    avgWakeTime: '06:30',
    avgActiveHours: 6.5,
    frequentZones: ['走廊', '活动室', '花园'],
    nightLeaveCount: 2.1,
    weeklyAnomalies: 3,
    todayDeviation: 78,
    deviationSummary: '张大爷通常在 22:00 后不再离开房间，但今天凌晨 03:12 出现在 3 楼走廊，且持续静止超过 12 秒，系统判定为高风险异常活动。',
    weeklyActivityTrend: [
      { day: '周一', hours: 7.2 }, { day: '周二', hours: 5.8 }, { day: '周三', hours: 6.4 },
      { day: '周四', hours: 6.1 }, { day: '周五', hours: 4.5 }, { day: '周六', hours: 5.0 }, { day: '周日', hours: 3.2 },
    ],
    nightLeaveTrend: [
      { day: '周一', count: 1 }, { day: '周二', count: 2 }, { day: '周三', count: 1 },
      { day: '周四', count: 3 }, { day: '周五', count: 2 }, { day: '周六', count: 1 }, { day: '周日', count: 4 },
    ],
    riskEventTrend: [
      { day: '周一', count: 0 }, { day: '周二', count: 1 }, { day: '周三', count: 0 },
      { day: '周四', count: 1 }, { day: '周五', count: 0 }, { day: '周六', count: 0 }, { day: '周日', count: 2 },
    ],
  },
  {
    id: 'res-002',
    name: '王秀兰',
    room: 'B栋-302',
    age: 82,
    riskTags: ['压疮风险', '骨质疏松'],
    todayStatus: '久卧未动，已通知',
    avgWakeTime: '07:00',
    avgActiveHours: 4.2,
    frequentZones: ['床铺', '洗手间'],
    nightLeaveCount: 1.3,
    weeklyAnomalies: 2,
    todayDeviation: 65,
    deviationSummary: '王奶奶今天早上起床后没有像往常一样在 8 点前到走廊散步，且 50 分钟内未检测到翻身动作，系统判定为中风险异常。',
    weeklyActivityTrend: [
      { day: '周一', hours: 4.8 }, { day: '周二', hours: 4.1 }, { day: '周三', hours: 3.5 },
      { day: '周四', hours: 4.3 }, { day: '周五', hours: 4.0 }, { day: '周六', hours: 3.8 }, { day: '周日', hours: 2.1 },
    ],
    nightLeaveTrend: [
      { day: '周一', count: 1 }, { day: '周二', count: 1 }, { day: '周三', count: 2 },
      { day: '周四', count: 1 }, { day: '周五', count: 1 }, { day: '周六', count: 0 }, { day: '周日', count: 2 },
    ],
    riskEventTrend: [
      { day: '周一', count: 0 }, { day: '周二', count: 0 }, { day: '周三', count: 1 },
      { day: '周四', count: 0 }, { day: '周五', count: 0 }, { day: '周六', count: 1 }, { day: '周日', count: 1 },
    ],
  },
  {
    id: 'res-003',
    name: '陈国华',
    room: 'B栋-508',
    age: 75,
    riskTags: ['夜间离床', '行动不便'],
    todayStatus: '夜间离床未归，待确认',
    avgWakeTime: '06:00',
    avgActiveHours: 7.0,
    frequentZones: ['花园', '走廊', '餐厅'],
    nightLeaveCount: 3.5,
    weeklyAnomalies: 4,
    todayDeviation: 82,
    deviationSummary: '陈大爷平时夜间最多起身 1 次且 5 分钟内返回，但今天凌晨 02:16 离床后超过 15 分钟仍未归，且行动轨迹在卫生间方向中断，系统判定为高风险。',
    weeklyActivityTrend: [
      { day: '周一', hours: 7.5 }, { day: '周二', hours: 6.8 }, { day: '周三', hours: 7.1 },
      { day: '周四', hours: 5.2 }, { day: '周五', hours: 6.9 }, { day: '周六', hours: 7.3 }, { day: '周日', hours: 4.8 },
    ],
    nightLeaveTrend: [
      { day: '周一', count: 3 }, { day: '周二', count: 2 }, { day: '周三', count: 4 },
      { day: '周四', count: 5 }, { day: '周五', count: 3 }, { day: '周六', count: 3 }, { day: '周日', count: 4 },
    ],
    riskEventTrend: [
      { day: '周一', count: 1 }, { day: '周二', count: 0 }, { day: '周三', count: 1 },
      { day: '周四', count: 2 }, { day: '周五', count: 0 }, { day: '周六', count: 1 }, { day: '周日', count: 2 },
    ],
  },
  {
    id: 'res-004',
    name: '李明辉',
    room: 'A栋-102',
    age: 80,
    riskTags: ['认知障碍', '迷路风险'],
    todayStatus: '电梯口滞留，观察中',
    avgWakeTime: '05:45',
    avgActiveHours: 8.0,
    frequentZones: ['电梯口', '花园入口', '餐厅'],
    nightLeaveCount: 1.8,
    weeklyAnomalies: 5,
    todayDeviation: 45,
    deviationSummary: '李爷爷下午在电梯口停留超过 10 分钟，结合近期迷路记录，可能是找不到回房间的路，系统判定为中风险。',
    weeklyActivityTrend: [
      { day: '周一', hours: 8.2 }, { day: '周二', hours: 7.5 }, { day: '周三', hours: 6.8 },
      { day: '周四', hours: 8.1 }, { day: '周五', hours: 7.9 }, { day: '周六', hours: 5.3 }, { day: '周日', hours: 6.0 },
    ],
    nightLeaveTrend: [
      { day: '周一', count: 2 }, { day: '周二', count: 1 }, { day: '周三', count: 2 },
      { day: '周四', count: 1 }, { day: '周五', count: 2 }, { day: '周六', count: 1 }, { day: '周日', count: 3 },
    ],
    riskEventTrend: [
      { day: '周一', count: 1 }, { day: '周二', count: 2 }, { day: '周三', count: 1 },
      { day: '周四', count: 0 }, { day: '周五', count: 1 }, { day: '周六', count: 1 }, { day: '周日', count: 1 },
    ],
  },
  {
    id: 'res-005',
    name: '刘德华',
    room: 'B栋-205',
    age: 71,
    riskTags: ['步态不稳', '膝关节退化'],
    todayStatus: '楼梯口摔倒，护理员已到场',
    avgWakeTime: '06:15',
    avgActiveHours: 5.5,
    frequentZones: ['楼梯口', '餐厅', '康复区'],
    nightLeaveCount: 0.8,
    weeklyAnomalies: 1,
    todayDeviation: 92,
    deviationSummary: '刘叔叔平时活动范围集中在 2 层，今天早上 9:15 突然出现在 1 层楼梯口且发生跌倒，结合膝关节退化病史，系统判定为紧急异常。',
    weeklyActivityTrend: [
      { day: '周一', hours: 5.8 }, { day: '周二', hours: 5.2 }, { day: '周三', hours: 6.0 },
      { day: '周四', hours: 5.5 }, { day: '周五', hours: 4.8 }, { day: '周六', hours: 5.1 }, { day: '周日', hours: 3.5 },
    ],
    nightLeaveTrend: [
      { day: '周一', count: 1 }, { day: '周二', count: 0 }, { day: '周三', count: 1 },
      { day: '周四', count: 1 }, { day: '周五', count: 0 }, { day: '周六', count: 1 }, { day: '周日', count: 2 },
    ],
    riskEventTrend: [
      { day: '周一', count: 0 }, { day: '周二', count: 0 }, { day: '周三', count: 0 },
      { day: '周四', count: 0 }, { day: '周五', count: 0 }, { day: '周六', count: 0 }, { day: '周日', count: 1 },
    ],
  },
];

export const mockEmergencyPlans: EmergencyPlan[] = [
  {
    id: 'plan-fall',
    eventType: '老人摔倒',
    icon: 'mdi:human-fall-down',
    riskLevel: 'critical',
    estimatedMinutes: 8,
    status: 'idle',
    currentStepIndex: 0,
    steps: [
      { id: 'step-fall-1', order: 1, title: '确认老人意识状态', note: '轻声呼唤老人姓名，观察是否有回应，切勿大声叫喊或摇晃身体。', knowledgeRef: '跌倒应急处理流程 · 第1条', status: 'pending' },
      { id: 'step-fall-2', order: 2, title: '观察是否出血或明显骨折', note: '检查头部、四肢、髋部是否有外伤或异常角度，如有出血先用干净布料按压止血。', knowledgeRef: '跌倒应急处理流程 · 第3条', status: 'pending' },
      { id: 'step-fall-3', order: 3, title: '不要盲目移动老人', note: '除非现场有二次危险（如火灾），否则保持老人原地不动，等待医护到场。', knowledgeRef: '跌倒应急处理流程 · 第3条', status: 'pending' },
      { id: 'step-fall-4', order: 4, title: '通知医护人员到场', note: '对讲机呼叫值班医护，说明老人状态、跌倒位置和疑似原因。', knowledgeRef: '老年人突发疾病观察要点 · 第4条', status: 'pending' },
      { id: 'step-fall-5', order: 5, title: '记录事件并生成护理报告', note: '记录跌倒时间、地点、姿态、周围环境、老人当前状态，系统将自动生成护理报告。', knowledgeRef: '跌倒应急处理流程 · 第5条', status: 'pending' },
    ],
  },
  {
    id: 'plan-leave',
    eventType: '离床未归',
    icon: 'mdi:bed-alert',
    riskLevel: 'high',
    estimatedMinutes: 6,
    status: 'idle',
    currentStepIndex: 0,
    steps: [
      { id: 'step-leave-1', order: 1, title: '确认老人离床时间', note: '查看系统记录的离床时间点，判断是否超过 10 分钟安全阈值。', knowledgeRef: '夜间离床风险处置规范 · 第1条', status: 'pending' },
      { id: 'step-leave-2', order: 2, title: '优先检查卫生间和走廊', note: '夜间离床最常见目的地是卫生间，先到卫生间和相邻走廊查看。', knowledgeRef: '夜间离床风险处置规范 · 第2条', status: 'pending' },
      { id: 'step-leave-3', order: 3, title: '轻声询问是否需要帮助', note: '找到老人后不要惊吓，轻声询问是否需要搀扶或陪同返回。', knowledgeRef: '夜间离床风险处置规范 · 第3条', status: 'pending' },
      { id: 'step-leave-4', order: 4, title: '如发现跌倒立即启动跌倒流程', note: '如果老人倒在地面，不要搬动，立即切换到跌倒应急流程。', knowledgeRef: '夜间离床风险处置规范 · 第4条', status: 'pending' },
      { id: 'step-leave-5', order: 5, title: '陪同老人返回床位并确认安全', note: '确认老人回到床上，调整被褥和室温，必要时增设夜灯。', knowledgeRef: '夜间离床风险处置规范 · 第5条', status: 'pending' },
    ],
  },
  {
    id: 'plan-smoke',
    eventType: '烟火异常',
    icon: 'mdi:fire-alert',
    riskLevel: 'high',
    estimatedMinutes: 10,
    status: 'idle',
    currentStepIndex: 0,
    steps: [
      { id: 'step-smoke-1', order: 1, title: '确认烟雾来源位置', note: '查看系统定位的烟雾发生区域，判断是茶水间、厨房还是设备间。', knowledgeRef: '火灾隐患初步处理流程 · 第2条', status: 'pending' },
      { id: 'step-smoke-2', order: 2, title: '判断是否为设备故障', note: '检查附近电器设备是否在运行，是否有焦糊气味或异常发热。', knowledgeRef: '火灾隐患初步处理流程 · 第2条', status: 'pending' },
      { id: 'step-smoke-3', order: 3, title: '如确认明火立即启动消防疏散', note: '拨打 119，按消防预案引导老人撤离，优先协助行动不便者。', knowledgeRef: '火灾隐患初步处理流程 · 第3条', status: 'pending' },
      { id: 'step-smoke-4', order: 4, title: '如为设备异常关闭电源并通风', note: '关闭故障设备电源，打开门窗通风，通知维修人员到场。', knowledgeRef: '火灾隐患初步处理流程 · 第4条', status: 'pending' },
      { id: 'step-smoke-5', order: 5, title: '填写专项报告并上报安全主管', note: '所有烟火事件无论大小，都必须填写专项报告并在当天上报安全主管。', knowledgeRef: '火灾隐患初步处理流程 · 第5条', status: 'pending' },
    ],
  },
  {
    id: 'plan-still',
    eventType: '长时间静止',
    icon: 'mdi:sleep',
    riskLevel: 'high',
    estimatedMinutes: 5,
    status: 'idle',
    currentStepIndex: 0,
    steps: [
      { id: 'step-still-1', order: 1, title: '查看静止持续时间', note: '确认系统记录的静止开始时间，超过 30 分钟需要重点关注。', knowledgeRef: '老年人突发疾病观察要点 · 第1条', status: 'pending' },
      { id: 'step-still-2', order: 2, title: '现场观察老人呼吸和面色', note: '注意观察胸腔是否有起伏，面色是否正常，有无出汗或嘴唇发紫。', knowledgeRef: '老年人突发疾病观察要点 · 第1条', status: 'pending' },
      { id: 'step-still-3', order: 3, title: '轻声呼唤并观察反应', note: '轻拍床边或肩膀，呼唤老人姓名，观察意识是否清醒。', knowledgeRef: '老年人突发疾病观察要点 · 第2条', status: 'pending' },
      { id: 'step-still-4', order: 4, title: '如无反应立即通知医护', note: '如老人无意识反应或疑似心梗脑卒中，立即拨打 120 并通知值班医护。', knowledgeRef: '老年人突发疾病观察要点 · 第3条', status: 'pending' },
      { id: 'step-still-5', order: 5, title: '协助老人调整体位', note: '确认安全后协助翻身或调整体位，检查被褥和室温。', knowledgeRef: '久卧未动与压疮风险评估', status: 'pending' },
    ],
  },
  {
    id: 'plan-illness',
    eventType: '疑似突发疾病',
    icon: 'mdi:heart-pulse',
    riskLevel: 'critical',
    estimatedMinutes: 12,
    status: 'idle',
    currentStepIndex: 0,
    steps: [
      { id: 'step-ill-1', order: 1, title: '快速评估老人意识状态', note: '观察老人是否清醒，能否正常应答，有无言语不清或意识模糊。', knowledgeRef: '老年人突发疾病观察要点 · 第1条', status: 'pending' },
      { id: 'step-ill-2', order: 2, title: '判断疑似疾病类型', note: '单侧肢体无力、口角歪斜疑似脑卒中；胸痛、出汗、呼吸困难疑似心梗。', knowledgeRef: '老年人突发疾病观察要点 · 第2条', status: 'pending' },
      { id: 'step-ill-3', order: 3, title: '立即拨打 120 并通知值班医护', note: '所有疑似突发疾病事件需在 3 分钟内通知值班医护。', knowledgeRef: '老年人突发疾病观察要点 · 第4条', status: 'pending' },
      { id: 'step-ill-4', order: 4, title: '保持呼吸道通畅', note: '将老人调整为侧卧位或半卧位，松开衣领，避免围观保持空气流通。', knowledgeRef: '老年人突发疾病观察要点 · 第5条', status: 'pending' },
      { id: 'step-ill-5', order: 5, title: '记录关键时间点和症状变化', note: '记录发病时间、初始症状、症状变化过程，供急救人员参考。', knowledgeRef: '老年人突发疾病观察要点 · 第4条', status: 'pending' },
      { id: 'step-ill-6', order: 6, title: '准备交接和家属通知', note: '整理老人病历、用药记录，准备与急救人员交接，同步通知家属。', knowledgeRef: '护理员巡房记录标准 · 第3条', status: 'pending' },
    ],
  },
];
